### ISSUE TITLE
Dynamic Titles

### ISSUE THREAD

**Issue by JasonAizkalns** [thomasp85/tweenr#10]
Would it be possible to add dynamic titles to use in conjunction with `gg_animate`. For example:

```
ts <- split(gapminder, gapminder$year)

tf <- tween_states(ts, tweenlength = 2, statelength = 1, ease = 'cubic-in-out', nframes = 50)

p <- ggplot(data = tf, aes(x = gdpPercap, y = lifeExp, size = pop, color = continent, frame = .frame)) +
  geom_point() +
  scale_x_log10() +
  ggtitle("Title")

gg_animate(p, interval = 0.2)
```

![file25d46f76c1](https://cloud.githubusercontent.com/assets/5184911/19046786/f565bade-896c-11e6-8783-bcf96d30b245.gif)

Notice that this has a static `Title` and then the `frame` from `frame = .frame`.

**Comment by thomasp85** [comment]
I don't think this is possible to solve in tweenr as it is a feature of gganimate
