### ISSUE TITLE
Examples in README do not work anymore with last gganimate dev version

### ISSUE THREAD

**Issue by cderv** [thomasp85/tweenr#11]
Hi, 

In last dev version of [gganimate](https://github.com/dgrtwo/gganimate), @dgrtwo changed `gg_animate` to `gganimate` with more changes on the way GIF are saved.

It is a breaking change for `README.md` examples when we install with 
`devtools::install_github("dgrtwo/gganimate")`. We need to install last working version `dgrtwo/gganimate@26ec501` with `gg_animate`

As it is curently Work In Progress for `gganimate`, we maybe should wait for final work but as I wanted to try `tweenr` I stumbled upon these non working examples. 

I thought it would be valuable to report this.

**Comment by jvcasill** [comment]
I can confirm that this is still the case. The examples produce errors. Moreover, I tried changing  ```gg_animate()```  to ```gganimate()``` and an infinite loop of plots was created on my desktop (I had to force quit).
