### ISSUE TITLE
Making an animation using tween_appear()

### ISSUE THREAD

**Issue by padpadpadpad** [thomasp85/tweenr#12]
Hi

I am trying to create an animation of my first bicycle ride of 2017. I have a data frame with latitude longitude gradient and n (indicating the order of points).

I used `tween_appear()` to interpolate between the points but it is not clear to me how to use `.age` and `.frame` to create an animation with `gganimate()`.

Here is some sample code, I have dputted the data into a [gist](https://gist.github.com/padpadpadpad/7e58a5e0931897bbf8c0e0a4565ba96a) to save space in this issue.

The map in the code creates the animation for `lat_lon` as I could not work out how to do it with the `tween_data`.

```r
# data
lat_lon <- data_from_link

# make up new data using tweenr
tween_data <- tween_appear(lat_lon, 'n', nframes = 200)

# make a bbox
bbox <- ggmap::make_bbox(lat_lon$lon, lat_lon$lat, f = 0.3)
# get map
map <- suppressWarnings(suppressMessages(get_map(bbox, maptype = 'satellite')))

# plot of just the lat_lon data
le_plot <- ggmap(map) +
  coord_fixed(ratio = 1) +
  theme(axis.title = element_blank()) +
  geom_path(aes(x = lon, y = lat,  col = grad, frame = n, cumulative = T), data = lat_lon, size = 2) +
  coord_cartesian() +
  scale_color_distiller('Gradient (%)', palette = 'Spectral') +
  facet_wrap(~ .frame)

animation::ani.options(interval = 1/24)
gg_animate(le_plot,  'first_ride_2017.gif', title_frame = F)

```

Any tips or help much appreciated.

**Comment by sctyner** [comment]
@padpadpadpad I am having similar struggles with the `tween_appear` function. Here's a solution I came up with, color added for emphasis of the age variable. 
```
# code from tween_appear help file
data <- data.frame(
  x = rnorm(100),
  y = rnorm(100),
  time = sample(50, 100, replace = TRUE)
)
data <- tween_appear(data, 'time', nframes = 200)
# create a variable for them to appear
data$.alpha <- as.numeric(data$.age > 0)
# plot it
p <- ggplot(data = data, aes(x =x, y = y , frame = .frame, color = .age, alpha = .alpha)) + 
                 geom_point() + 
                 scale_alpha_identity()
animation::ani.options(interval = 1/15)
gganimate(p, "testtweenappear.gif", title_frame = F)
```
![testtweenappear](https://cloud.githubusercontent.com/assets/6137322/23581353/c1458148-00d7-11e7-839d-0c98a2e257cf.gif)

I'd also be interested in what @thomasp85 intended this `tweer_appear`'d data to look like when visualized, because it is so cool and can be really useful.

**Comment by dmi3kno** [comment]
Just now I did tween_elements() immediately followed by tween_appear() for building a continuing line. Check it out!
https://www.kaggle.com/dmi3kno/leaderboard-shakeup-storyline-chart/

**Comment by thomasp85** [comment]
The new `tween_events` is probably the `tween_appear` we all needed after all...
