### ISSUE TITLE
Frames dropped when using tweenr and gganimate

### ISSUE THREAD

**Issue by JB70** [thomasp85/tweenr#14]
[Evolution-dataset-GitHub.xlsx](https://github.com/thomasp85/tweenr/files/888400/Evolution-dataset-GitHub.xlsx)

With the given data set and the code below, the resulting animation should end in the year 2015, not 1995 as it does.

Here is the code. A error in the code?

`#### Reproducible code - error with missing frames in gganmate using tweenr ####

sessionInfo()

### Packages ###
install.packages("ggplot2")
install.packages("dplyr")
install.packages("tweenr")
install.packages("readxl")
install.packages("xlsx")
install.packages("gapminder")
install.packages("ggrepel")
devtools::install_github("dgrtwo/gganimate")

### Libraries ###
library("ggplot2")
library("tweenr")
library("gganimate")
library("dplyr")
library("readxl")
library("xlsx")
library("ggrepel")

### Working Directory ###
getwd()
setwd("C:/Users/brockjue/Documents/JB B/Fujitsu Americas/Marketing Intelligence/R/Animations")
getwd()

### Options ###
options(scipen = 999)

### Raw Data - Data Entry/ Import ###
IT.industry <- read_excel("~/JB B/Fujitsu Americas/Marketing Intelligence/R/Animations/Evolution-dataset-GitHub.xlsx", 
                          sheet = "timeline3-R", na = "NA")

## key variables as factor and integer and sorting - full dataset ##
IT.industry$Company <- as.factor(IT.industry$Company)
IT.industry$Company <- ordered(IT.industry$Company)
IT.industry$Year <- as.integer(IT.industry$Year)

## Interpolations with tweenr full dataset ##
IT.industry.tweenr <- IT.industry %>% split(.$Year) %>% tweenr::tween_states(tweenlength = 0.1, statelength = 0, ease = "linear", nframes = 600)
IT.industry.tweenr$FTEs2 <- IT.industry.tweenr$FTEs/1000
IT.industry.tweenr$Company <- ordered(IT.industry.tweenr$Company)

### Data Display ###

evolution3 <- ggplot(IT.industry.tweenr,
                          aes(x = Year, y = Profitability2, size = Revenue3, color = Company, frame = Year, cumulative = FALSE)) +
  geom_point(alpha = .1, stroke = 0) +
  geom_text(label = IT.industry.tweenr$Company, size = 3, hjust = 1, vjust = 1) +
  #geom_hline(yintercept = 0) +
  ggtitle("Year: ") +
  scale_size_continuous(range = c(1,20)) +
  theme_minimal() +
  theme(legend.position="none") +
  scale_x_continuous(limits = c(1950, 2020), breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) +
  scale_y_continuous(labels = scales::percent, limits = c(-0.8,0.8)) +
  xlab("Year") + ylab("Profitability (Net income / revenue")
evolution3
gganimate(evolution3, "Evolution3-GitHub.mp4", interval=0.1, title_frame = TRUE, ani.width=800, ani.height=400)

#### END All ####`

sessionInfo:
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by thomasp85** [comment]
Can I get you to make a more minimal example. Specifically investigate whether the error happens on the tweenr or ggplot2/gganimate ends (simply look for the range of Year after you have prepared the data). If you find that the error is indeed happening in tweenr please reduce your code to the bare minimum for the error to survive and repost

**Comment by mrecos** [comment]
Rerunning the example above with new installs of all packages, including `devtools::install_github("thomasp85/tweenr")`, I was unable to find an issue with the tween'd code ending at 1995. I cannot use `gganimate` on this machine, so the issue may be there.

The only comparable issue I came across was the tween's data ending at 2014 instead of 2015 (the final year of data) if `statelength = 0` in the `tween_states()` call of the above code.  If `statelength > 0`, the tween'd data includes 2015.  I traced this to the results from:

 `numeric_state_interpolator <- function(data, states) {
  .Call('tweenr_numeric_state_interpolator', PACKAGE = 'tweenr', data, states)
}`

However, I highly doubt that this is the source of an error that results in the animation ceasing at 1995.  For that I would check with `gganimate()` or include a more concise reproducible example as suggested above.

**Comment by JB70** [comment]
I checked. Sorry for the delay. The issue appears to be unrelated to tweenr. The resulting data frame from the code above looks fine throughout; no 1995 cut off or peculiarities around the year 1995. So the error must be the handover to gganimate. Either gganimate intrinsic or the link to the MPEG4 generator. I'll try the same code on a Mac (vs PC) to see whether it ends with 1995 too.

**Comment by JB70** [comment]
I tried the code on a Mac and it works. The error must have to do with the ImageMagick/ffmpeg installation on the Windows machine rather than the gganimate package.

**Comment by thomasp85** [comment]
I'm closing as this seems unrelated to tweenr
