### ISSUE TITLE
Making dancing ball.gif

### ISSUE THREAD

**Issue by anabento** [thomasp85/tweenr#16]
Hi I try to use the code for the dancing ball but i get the following error message. Can you help?
Executing: 
convert -loop 0 -delay 6.66666666666667 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png
    Rplot9.png Rplot10.png Rplot11.png Rplot12.png Rplot13.png Rplot14.png Rplot15.png Rplot16.png Rplot17.png Rplot18.png Rplot19.png
    Rplot20.png Rplot21.png Rplot22.png Rplot23.png Rplot24.png Rplot25.png Rplot26.png Rplot27.png Rplot28.png Rplot29.png Rplot30.png
    Rplot31.png Rplot32.png Rplot33.png Rplot34.png Rplot35.png Rplot36.png Rplot37.png Rplot38.png Rplot39.png Rplot40.png Rplot41.png
    Rplot42.png Rplot43.png Rplot44.png Rplot45.png Rplot46.png Rplot47.png Rplot48.png Rplot49.png Rplot50.png Rplot51.png Rplot52.png
    Rplot53.png Rplot54.png Rplot55.png Rplot56.png Rplot57.png Rplot58.png Rplot59.png Rplot60.png Rplot61.png Rplot62.png Rplot63.png
    Rplot64.png Rplot65.png Rplot66.png Rplot67.png Rplot68.png Rplot69.png Rplot70.png Rplot71.png Rplot72.png Rplot73.png Rplot74.png
    Rplot75.png Rplot76.png Rplot77.png Rplot78.png Rplot79.png Rplot80.png Rplot81.png Rplot82.png Rplot83.png Rplot84.png Rplot85.png
    Rplot86.png Rplot87.png Rplot88.png Rplot89.png Rplot90.png Rplot91.png Rplot92.png Rplot93.png Rplot94.png Rplot95.png Rplot96.png
    Rplot97.png Rplot98.png Rplot99.png Rplot100.png Rplot101.png Rplot102.png Rplot103.png Rplot104.png Rplot105.png Rplot106.png
    Rplot107.png Rplot108.png Rplot109.png Rplot110.png Rplot111.png Rplot112.png Rplot113.png Rplot114.png Rplot115.png Rplot116.png
    Rplot117.png Rplot118.png Rplot119.png Rplot120.png Rplot121.png Rplot122.png Rplot123.png Rplot124.png Rplot125.png Rplot126.png
    Rplot127.png Rplot128.png Rplot129.png Rplot130.png Rplot131.png Rplot132.png Rplot133.png Rplot134.png Rplot135.png Rplot136.png
    Rplot137.png Rplot138.png Rplot139.png Rplot140.png Rplot141.png Rplot142.png Rplot143.png Rplot144.png Rplot145.png Rplot146.png
    Rplot147.png Rplot148.png Rplot149.png Rplot150.png Rplot151.png Rplot152.png Rplot153.png Rplot154.png Rplot155.png Rplot156.png
    Rplot157.png Rplot158.png Rplot159.png Rplot160.png Rplot161.png Rplot162.png Rplot163.png Rplot164.png Rplot165.png Rplot166.png
    Rplot167.png Rplot168.png Rplot169.png Rplot170.png Rplot171.png Rplot172.png Rplot173.png Rplot174.png Rplot175.png Rplot176.png
    Rplot177.png Rplot178.png Rplot179.png Rplot180.png Rplot181.png Rplot182.png Rplot183.png Rplot184.png Rplot185.png Rplot186.png
    Rplot187.png Rplot188.png Rplot189.png Rplot190.png Rplot191.png Rplot192.png Rplot193.png Rplot194.png Rplot195.png Rplot196.png
    Rplot197.png Rplot198.png Rplot199.png Rplot200.png Rplot201.png Rplot202.png Rplot203.png Rplot204.png Rplot205.png Rplot206.png
    Rplot207.png Rplot208.png Rplot209.png Rplot210.png Rplot211.png Rplot212.png Rplot213.png Rplot214.png Rplot215.png Rplot216.png
    Rplot217.png Rplot218.png Rplot219.png Rplot220.png Rplot221.png Rplot222.png Rplot223.png Rplot224.png Rplot225.png Rplot226.png
    Rplot227.png Rplot228.png Rplot229.png Rplot230.png Rplot231.png Rplot232.png Rplot233.png Rplot234.png Rplot235.png Rplot236.png
    Rplot237.png Rplot238.png Rplot239.png Rplot240.png Rplot241.png Rplot242.png Rplot243.png Rplot244.png Rplot245.png Rplot246.png
    Rplot247.png Rplot248.png Rplot249.png Rplot250.png Rplot251.png Rplot252.png Rplot253.png Rplot254.png Rplot255.png Rplot256.png
    Rplot257.png Rplot258.png Rplot259.png Rplot260.png Rplot261.png Rplot262.png Rplot263.png Rplot264.png Rplot265.png Rplot266.png
    Rplot267.png Rplot268.png Rplot269.png Rplot270.png Rplot271.png Rplot272.png Rplot273.png Rplot274.png Rplot275.png Rplot276.png
    Rplot277.png Rplot278.png Rplot279.png Rplot280.png Rplot281.png Rplot282.png Rplot283.png Rplot284.png Rplot285.png Rplot286.png
    Rplot287.png Rplot288.png Rplot289.png Rplot290.png Rplot291.png Rplot292.png Rplot293.png Rplot294.png Rplot295.png Rplot296.png
    Rplot297.png Rplot298.png Rplot299.png Rplot300.png Rplot301.png Rplot302.png Rplot303.png Rplot304.png Rplot305.png Rplot306.png
    Rplot307.png Rplot308.png Rplot309.png Rplot310.png Rplot311.png Rplot312.png Rplot313.png Rplot314.png Rplot315.png Rplot316.png
    Rplot317.png Rplot318.png Rplot319.png Rplot320.png Rplot321.png Rplot322.png Rplot323.png Rplot324.png Rplot325.png Rplot326.png
    Rplot327.png Rplot328.png Rplot329.png Rplot330.png Rplot331.png Rplot332.png Rplot333.png Rplot334.png Rplot335.png Rplot336.png
    Rplot337.png Rplot338.png Rplot339.png Rplot340.png Rplot341.png Rplot342.png Rplot343.png Rplot344.png Rplot345.png Rplot346.png
    Rplot347.png Rplot348.png Rplot349.png Rplot350.png Rplot351.png Rplot352.png Rplot353.png Rplot354.png Rplot355.png Rplot356.png
    Rplot357.png Rplot358.png Rplot359.png Rplot360.png Rplot361.png Rplot362.png Rplot363.png Rplot364.png Rplot365.png Rplot366.png
    Rplot367.png Rplot368.png Rplot369.png Rplot370.png Rplot371.png Rplot372.png Rplot373.png Rplot374.png Rplot375.png 'dancing
    ball.gif'
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.
convert: no images defined `dancing ball.gif' @ error/convert.c/ConvertImageCommand/3254.
an error occurred in the conversion... see Notes in ?im.convert
Error in file(file, "rb") : cannot open the connection
In addition: Warning message:
In file(file, "rb") :
  cannot open file '/Users/anabento/Desktop/dancing ball.gif': No such file or directory

**Comment by thomasp85** [comment]
This seems to be a problem with the `animation` or `gganimate` package
