### ISSUE TITLE
NSE evaluation, similar to dplyr

### ISSUE THREAD

**Issue by dgrtwo** [thomasp85/tweenr#2]
This package is excellent and I'll be interested in integrating it into the gganimate package!

Would you be open to changing `tween_elements` etc to take bare names instead of strings for the columns? For example, instead of

```
data %>%
    tween_elements('time', 'group', 'ease', nframes = 100)
```

It could be used like:

```
data %>%
    tween_elements(time, group, ease, nframes = 100)
```

This could be implemented as [described here](https://cran.r-project.org/web/packages/lazyeval/vignettes/lazyeval.html), by making two versions of the functions, e.g. `tween_elements_` and `tween_elements`. The advantages:
- When used in a dplyr pipeline, people may be accustomed to using dplyr's, tidyr's, and ggplot2's use of bare expressions over passing strings of columns
- This API would be consistent with future features where people could perform operations in the `tween_elements` call, e.g. `tween_elements(time = round(year, -2)...)`, or where a bare string for `ease` would be interpreted as an argument (e.g. someone could just put `tween_elements(...ease = "cubic-in-out"... without having to add the`ease column to the data).
- People could still call `tween_elements_` if they wanted to provide string column names

**If you are open to this change, I would be very happy to implement it myself and submit it as a pull request**

**Comment by thomasp85** [comment]
I had this in mind, but somehow it didn't make it to the release. If you want you're welcome to make a PR, but I'll do it myself eventually...
