### ISSUE TITLE
code for the examples?

### ISSUE THREAD

**Issue by skanskan** [thomasp85/tweenr#3]
Could you please write the code of the a animations on the main github tweenr page or the help files, please?
With an example with gganimate, please.

**Comment by thomasp85** [comment]
Will happen...

**Comment by thomasp85** [comment]
Fixed with 5b3f66b

**Comment by skanskan** [comment]
Great

**Comment by skanskan** [comment]
Hello.

I've just tried both examples and I get this error in both cases:

Executing: 
""C:\Program Files\ImageMagick-6.9.2-Q8\convert.exe" -loop 0 -delay 6.66666666666667 Rplot1.png Rplot2.png
.....
Rplot374.png Rplot375.png "dancing ball.gif""
Output at: dancing ball.gif
opening gganimate file stored at
Error in shell.exec(file) : invalid 'file' argument

I know this isn't a problem with your package but with ImageMagic or gganimate.

**Comment by thomasp85** [comment]
Hmm. Not on Windows myself. Try switching space for underscore in the filename..?
