### ISSUE TITLE
g++-4.4 required for installation?

### ISSUE THREAD

**Issue by amarder** [thomasp85/tweenr#34]
I tried installing tweenr with devtools 

```
devtools::install_github("thomasp85/tweenr")
```

but I'm getting the following error:

```
g++-4.4 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
/bin/sh: g++-4.4: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘tweenr’
```

I tried installing gcc version 4.4 with homebrew (I'm on a Mac), but it looks like the oldest version available is 4.9. Any thoughts on what might be going wrong? I'm going to try reinstalling Rcpp and see if that helps.

Thanks! Andrew

**Comment by amarder** [comment]
This looks like an Rcpp issue (installing on Mac is hard). FAQ 2.10 in this document tries to address the issue: https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf

This is not an issue with tweenr.

**Comment by thomasp85** [comment]
Mac generally uses the clang compiler in favour of gcc, and generally the clang version bundled with the developer command line tools are sufficient. I’ve never experienced problems on my Mac...
