### ISSUE TITLE
Change to MIT license

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/tweenr#38]
This package changed licensing some time ago without getting the consent from contributors. This was just me not being aware of the finer prints of GPL licensing (incidentallly this was also why I wanted to change it). So previous contributors (@jimhester, @QuLogic, @lgatto, @lselzer, @jpolonsky) if you are against this change, reply to this thread and I’ll make sure to undo your contributions. I’ll close this issue in a month or so and consider it resolved if no one responds

**Comment by QuLogic** [comment]
Pretty sure all I did was remove some executable bits, which is far from copyrightable, so no issues from me.
