### ISSUE TITLE
Inconsistent number of frames created by 'tween_state'

### ISSUE THREAD

**Issue by trevorld** [thomasp85/tweenr#44]
I'm noticing that ``tween_state`` calculates one fewer frame if its ``.data`` argument is not the result of a prior "tween" than if its ``.data`` argument is the result of a prior "tween".  

For an example with three (identical) states stored in a list that is "reduced" by ``tween_state`` with ``nframes=2`` I'm observing no transition frame for the tween of the first two states and one transition frame for the tween of the second and third states.

```
> library("tweenr")
> df <- data.frame(piece_type = "pawn", color = "black",
+                  x = 1.0, y = 1.0, id = 1, stringsAsFactors = FALSE)
> dfs <- list(df, df, df)
> print(dfs)
[[1]]
  piece_type color x y id
1       pawn black 1 1  1

[[2]]
  piece_type color x y id
1       pawn black 1 1  1

[[3]]
  piece_type color x y id
1       pawn black 1 1  1

> fn <- function(df1, df2) tween_state(df1, df2, ease = 'linear', nframes = 2, id = id)
> df <- Reduce(fn, dfs)
> print(df)
   piece_type     color x y id .id     .phase .frame
1        pawn     black 1 1  1   1        raw      1
2        pawn     black 1 1  1   1        raw      2
21       pawn #000000FF 1 1  1   1 transition      3
11       pawn     black 1 1  1   1        raw      4
```

**Comment by trevorld** [comment]
Looking at the behaviour of other functions like ``tween_numeric`` then it seems to me that the number of frames in ``tween_state`` is one higher than it should if the ``.data`` argument is the result of a prior "tween" but the number of frames is correct if the ``.data`` argument is not the result of a prior ``tween`` i.e. ``tween_numeric(1:3, 2)`` does not compute a transition while ``tween_numeric(1:3, 3)`` computes one transition between each state.

**Comment by thomasp85** [comment]
If you want the same semantics as `tween_numeric` then you should use `tween_states`. 

`tween_state` is part of the newer interface meant to chain calls together where it makes sense to use the last frame as part of the new tween and thus create one less frame

**Comment by trevorld** [comment]
> where it makes sense to use the last frame as part of the new tween and thus create one less frame

Is ``tween_state`` actually creating one less frame to account for using the last frame of the previous tween?  I think I'm observing an extra frame in such cases where there shouldn't be one i.e. the second ``nframes = 2`` tween seems to correspond to the 3 frames 2, 3, and 4 whereas shouldn't it just have 2 frames (i.e. the frames 2 and 4 and omit 3)?

>  you should use tween_states

I can't use ``tween_states`` for my actual use case which involves a list of data frames each with a variable number of rows.

**Comment by trevorld** [comment]
A simpler reproducible example of the "bug":
```
> library("tweenr")
> (df_normal <- data.frame(x = 1, id = 1))
  x id
1 1  1
> (df_previously_tweened <- tween_state(df_normal, df_normal, 'linear', nframes = 1, id = id))
  x id .id .phase .frame
1 1  1   1    raw      1
> tween_state(df_normal, df_normal, 'linear', nframes = 1, id = id)
  x id .id .phase .frame
1 1  1   1    raw      1
> tween_state(df_previously_tweened, df_normal, 'linear', nframes = 1, id = id)
  x id .id .phase .frame
1 1  1   1    raw      1
2 1  1   1    raw      2
> tween_state(df_normal, df_normal, 'linear', nframes = 2, id = id)
  x id .id .phase .frame
1 1  1   1    raw      1
2 1  1   1    raw      2
> tween_state(df_previously_tweened, df_normal, 'linear', nframes = 2, id = id)
   x id .id     .phase .frame
1  1  1   1        raw      1
2  1  1   1 transition      2
11 1  1   1        raw      3
> tween_state(df_normal, df_normal, 'linear', nframes = 3, id = id)
   x id .id     .phase .frame
1  1  1   1        raw      1
2  1  1   1 transition      2
11 1  1   1        raw      3
> tween_state(df_previously_tweened, df_normal, 'linear', nframes = 3, id = id)
   x id .id     .phase .frame
1  1  1   1        raw      1
2  1  1   1 transition      2
3  1  1   1 transition      3
11 1  1   1        raw      4
```

**Comment by thomasp85** [comment]
I misspoke in the last reply - tween_state will use the start frame as part of the number of frames if, and only if, it is not the end of a previous tween. This is done in order to make the final frame numbers predictable, i.e. tweening over ten frames from d1 to d2, and then over 10 frames to d3 will result in 20 frames
