### ISSUE TITLE
Interpolate between as.POSIXct()

### ISSUE THREAD

**Issue by ottlngr** [thomasp85/tweenr#6]
I have a data.frame containing information on stops and arrival/departure times of an arbitrary train:
```

                     name      id       lon      lat routeIdx         datetime_ct
1          Hamburg-Altona 8002553  9.935174 53.55270        0 2016-06-13 06:20:00
2         Hamburg Dammtor 8002548  9.989568 53.56075        1 2016-06-13 06:28:00
3             Hamburg Hbf 8002549 10.006908 53.55273        2 2016-06-13 06:34:00
4          Berlin-Spandau 8010404 13.197530 52.53447        3 2016-06-13 08:10:00
5       Berlin Hbf (tief) 8098160 13.369548 52.52559        4 2016-06-13 08:27:00
6         Berlin Südkreuz 8011113 13.365314 52.47504        5 2016-06-13 08:34:00
7  Lutherstadt Wittenberg 8010222 12.662286 51.86781        6 2016-06-13 09:09:00
8              Bitterfeld 8010050 12.316848 51.62286        7 2016-06-13 09:26:00
9             Leipzig Hbf 8010205 12.383333 51.34655        8 2016-06-13 09:48:00
10             Erfurt Hbf 8010101 11.038501 50.97255        9 2016-06-13 10:34:00
11                  Fulda 8000115  9.683980 50.55472       10 2016-06-13 11:57:00
12           Würzburg Hbf 8000260  9.935777 49.80179       11 2016-06-13 12:33:00
13           Nürnberg Hbf 8000284 11.082989 49.44561       12 2016-06-13 13:31:00
14         Ingolstadt Hbf 8000183 11.437335 48.74454       13 2016-06-13 14:05:00
15            München Hbf 8000261 11.558338 48.14023       14 2016-06-13 14:41:00
```
The column `datetime_ct` is `as.POSIXct()`:

```
> str(ice)
'data.frame':	15 obs. of  6 variables:
 $ name       : chr  "Hamburg-Altona" "Hamburg Dammtor" "Hamburg Hbf" "Berlin-Spandau" ...
 $ id         : chr  "8002553" "8002548" "8002549" "8010404" ...
 $ lon        : num  9.94 9.99 10.01 13.2 13.37 ...
 $ lat        : num  53.6 53.6 53.6 52.5 52.5 ...
 $ routeIdx   : num  0 1 2 3 4 5 6 7 8 9 ...
 $ datetime_ct: POSIXct, format: "2016-06-13 06:20:00" "2016-06-13 06:28:00" "2016-06-13 06:34:00" ...
```

I want to interpolate between the arrival/departure times to visualize the movement of the train as I did here: [https://twitter.com/0ttlngr/status/739212217489489920](https://twitter.com/0ttlngr/status/739212217489489920)

I have data for one train only, therefore I have just a single group:
```
ice$group <- 1
```
I want `tweenr` to interpolate linearly:
```
ice$ease <- "linear"
```

And now I use `tween_elements()` to interpolate:
```
> tween_elements(ice, time = "datetime_ct", group = "group", ease = "ease", nframes = 100)

Error in `/.difftime`((data[[time]] - timerange[1]), framelength) : 
  second argument of / cannot be a "difftime" object
```

I wonder if it's a mistake of mine or if there's a problem with `tween_elements()`.

**Comment by thomasp85** [comment]
From the top of my head (I've not tested this), you need to convert the time column to numeric. This could probably be automated within tweenr, but I simply did not think that long when I wrote it. Converting a POSIXct object to a numeric will give the time elapsed since a reference date, so the relative difference between the rows will be conserved...

I'll think about supporting POSIX in the time column natively for a future update...

Let me know if this solves it

**Comment by ottlngr** [comment]
Yes, that's what I did to create the animation on Twitter. I just thought POSIX is supported because you list it in your README.

Maybe I'll do this myself and send you a PR.

**Comment by thomasp85** [comment]
Interpolation of POSIX is supported. In your example you use POSIX as time stamps - there is a subtle difference

**Comment by ottlngr** [comment]
Sorry, wasn't aware of that.
Anyway, great package! I'll close this issue.
